### ISSUE TITLE
Make css/js path configurable with cli parameter

### ISSUE THREAD

**Issue by pythononwheels** [pytest-dev/pytest-html#197]
Cause:
I need to use the standalone version since I cannot serve the default css/js paths ("/assets/"). 
So the generated report does not find the css/js. 

possible solution:
Would be a nice thing to make them configurable with a prefix path parameter like 
`--include-prefix=<prefix>   `
Default: `/assets` so everything stays the same.

So you can adapt the path to include it to existing apps already having a different static path prefix.

**Comment by BeyondEvil** [comment]
I agree @RibeiroAna! 

Would you feel comfortable contributing a PR for this @pythononwheels? I'm happy to guide you through it, should you need it.

Maybe name the flag `--assets-path` ?

**Comment by pythononwheels** [comment]
Yes. Cool. Let‘s do it.
—assets-path sounds reasonable.

**Comment by BeyondEvil** [comment]
If you need help/pointers from me @pythononwheels, your best bet is to reach to me on Slack in the Selenium:python channel.

https://seleniumhq.slack.com/messages/C5PJXA814

I'm `jimboslice` there.

**Comment by RibeiroAna** [comment]
@pythononwheels I remember that Pytest-HTML has the functionality of setting a path to the desired location of the file (so instead of doing something like `--html=report.html` you can do something like `--html=/my/path/report.html`, I think it solves your issue! I'll close this topic, but if does not solve your issue, feel free to reopen.
