### ISSUE TITLE
optional publish option

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest-html#249]
Some CI systems do not have any option to collect/publish test results and even for developers running tests locally it may be inconvenient to share the html file product.

If pytest-html would have an option to upload the resulted html to a web server and return the sharable file, it would be much easier. The final patch could even by randomized in order to avoid overlapping.

This option could fully be controlled via two environment variables like:
```
PYTEST_HTML_PUBLISH_SSH=ssh://foo@my_server///var/www/html/reports
PYTEST_HTML_PUBLISH_URL=https://my.server/reports
```

The upload would be triggered by the presence of the variable, missing it would mean no upload to be performed.

Please comment on that feature request as if that is desired, I may try to implement it over a weekend.

**Comment by BeyondEvil** [comment]
I'm not against the idea, because I've had this "issue" myself (and solved it). But I do have concerns.

1. Separation of concerns. The plugin should generate an html report. Does also publishing the report really belong to the plugin?

2. This type of feature has a tendency to expand. There's a million and one different ways to publish something. How do we accommodate all different ways without bloating the plugin.

3. This would require more dependencies. What about users who doesn't want this functionality and now may be forced to do extra work for one reason or another? Some companies require audits (security, licensing, etc) for each dependency.

Here's what I suggest: Create a separate plugin. That way, we can make that plugin an _optional_ dependency (`pytest-html[publish]`). And if you make the plugin generic enough, it can be used to publish any artifact, so it will be useful for other projects.

I'm happy to help implement and maintain such a plugin if you want.

Thoughts @ssbarnea ?

**Comment by ssbarnea** [comment]
@BeyondEvil I was seeing that coming as I had that need in other places too. Unitest results, coverage and other stuff are likely to need publishing support.

Now the big question is the publishing plugin should be a pytest plugin, or tox plugin?

I kinda find weird that I was not able to find already existing plugins for doing this. It seems a very common use case.

**Comment by BeyondEvil** [comment]
> @BeyondEvil I was seeing that coming as I had that need in other places too. Unitest results, coverage and other stuff are likely to need publishing support.

Exactly!

> Now the big question is the publishing plugin should be a pytest plugin, or tox plugin?

Maybe it doesn't even need to be a plugin, it could just be a regular python package. 🤷‍♂ 

> I kinda find weird that I was not able to find already existing plugins for doing this. It seems a very common use case.

Agreed! After I had posted my comment, I also went looking, and I couldn't find anything either.

**Comment by RonnyPfannschmidt** [comment]
This is a task for reasonably complete ci systems, layering it somewhere else is just feature creep

**Comment by BeyondEvil** [comment]
> This is a task for reasonably complete ci systems, layering it somewhere else is just feature creep

While I agree that would be ideal, I've personally had use cases where the solution provided by the CI system (Travis, Circle, Bitbucket) has not been satisfactory (and I'm happy to provide examples to that fact). Understandably so because, like I said in an earlier comment, there's a million and one way to publish something (really take a file and put it somewhere else).

Having it in a plugin (or package) (separate from, in this case, `pytest-html`) provides users with an option to extend the behavior to fit there needs. If the solution that CI provides works for you - great! If not, well now there's an option.

Having it separate also deals with feature creep, at least to a certain extent. As for the "publishing" plugin, any feature creep there will be up to the maintainer(s) to deal with.

@RonnyPfannschmidt

**Comment by RonnyPfannschmidt** [comment]
@BeyondEvil im also well aware of the practically intentionally severely limited ci tools around

i still don't think this should be a pytest plugin, this should be a "suggested tool" whose main intend is to argument subpar ci systems with artefact publishing

**Comment by BeyondEvil** [comment]
Fair enough.

Do you see it as a library that we consume in the plugin or a standalone CLI (or something else)? @RonnyPfannschmidt

**Comment by RonnyPfannschmidt** [comment]
right now i beleive standalone command to be put into a deploy section on something like travis

**Comment by rochacbruno** [comment]
Usually what I do is to create a self contained html and paste to https://pste.eu/ I think one can pipe the html output to that website form easily.

**Comment by BeyondEvil** [comment]
That could be an option in the tool. 👍 @rochacbruno
