### ISSUE TITLE
Extras from reruns are attached to final test

### ISSUE THREAD

**Issue by VladimirPodolyan** [pytest-dev/pytest-html#374]
Deps:
- pytest==6.1.2
- pytest-rerunfailures==9.1.1
- pytest-selenium==2.0.1
- pytest-html==2.1.1/3.0.0

----

After updating `pytest-html` to `3.0.0` version in project requirements I got unexpected extras from `test reruns` in html report. Actually all extras from test reruns (logs/links/duration/screenshots) also applied to final test with failed/passed result.

### Ver 3.0.0
<img width="2266" alt="SM" src="https://user-images.githubusercontent.com/36446855/99747241-4ba94e00-2aeb-11eb-9fd6-e207f7ca2b8e.png">

### Ver 2.1.1
![SM1](https://user-images.githubusercontent.com/36446855/99748239-359c8d00-2aed-11eb-8102-bdfa59fa0514.png)

Ver 2.1.1 had a bug with missing screenshots, but other data correct. So my opinion that something was broken since ver 3.0.0

**Comment by gnikonorov** [comment]
Hey @VladimirPodolyan thanks for raising this issue! Let me try and make a reproducer on my end.

**Comment by gnikonorov** [comment]
For now, I'm thinking that every rerun should be its own entry in the table

**Comment by gnikonorov** [comment]
![Screen Shot 2020-11-28 at 10 38 31 AM](https://user-images.githubusercontent.com/13026015/100519460-0083e080-3166-11eb-8294-ba0d0b703e60.png)

It looks like we already have one entry per rerun, but the data is populating incorrectly

**Comment by gnikonorov** [comment]
I should have a PR up for this today or tomorrow, @VladimirPodolyan. Thank you for reporting this

**Comment by VladimirPodolyan** [comment]
@gnikonorov Thank for respond and fixing the issue!

**Comment by gnikonorov** [comment]
> @gnikonorov Thank for respond and fixing the issue! 

Of course @VladimirPodolyan ! I'll merge this in EOD today so it'll be available off of head and I'm planning to release to PyPI by the end of 12/2.

**Comment by gnikonorov** [comment]
Hi @VladimirPodolyan you can get this functionality by installing the latest version of pytest-html from [PyPI](https://pypi.org/project/pytest-html/)

**Comment by VladimirPodolyan** [comment]
@gnikonorov The report looks fine now. Thanks for the poke!

**Comment by gnikonorov** [comment]
> @gnikonorov The report looks fine now. Thanks for the poke!

Of course! Glad to hear it works as expected now.

**Comment by aryanrawat229** [comment]
**Still occurring in v4.2.0 with pytest-rerunfailures**

When using pytest-rerunfailures (2 reruns), extras set via rep.extras in pytest_runtest_makereport are duplicated across all rows (Failed + Rerun + Rerun). Each row shows all 3 attempts' screenshots and trace links instead of only its own.

**Setup:**

pytest-html: 4.2.0
pytest-rerunfailures: latest
Hook sets rep.extras fresh per attempt using item.execution_count to label files
Expected: Each row (Failed, Rerun 1, Rerun 2) shows only its own screenshot and trace link.

Actual: All 3 rows show all 3 attempts' extras (Trace 1, Trace 2, Trace 3 + Image 1/3 on every row).

Screenshot attached.

<img width="1882" height="882" alt="Image" src="https://github.com/user-attachments/assets/41c5f33a-557b-444f-b19b-0304c4abda04" />
