### ISSUE TITLE
Error or failure information can be collapsed

### ISSUE THREAD

**Issue by hailin-xiao** [pytest-dev/pytest-html#43]
Hi,

Could you please add a new feature that user could collapse the error or failure log? it's a little bit hard to find the useful information once there're hundreds of errors or failures in the report. 
For better understanding, I would like to give an example: <div class='log'><details>balabala</details></div>
Thanks very much and looking forward for that.

Regards,

Hailin

**Comment by davidedelvento** [comment]
@davehunt - I think this becomes even more important because of #44 (at least for some people).
I'll be happy to work on a rudimentary javascript implementation and make a PR, if no one is working on it already.

**Comment by hailin-xiao** [comment]
@davidedelvento @davehunt 
Thanks for your quick response. Actually, we have made a temporary solution to satisfy our project. It's to make some changes on main.js. Please refer to the changes listed below. Any comments are appreciated. Thanks

Hailin

![changes](https://cloud.githubusercontent.com/assets/17964912/15527221/19569c24-226b-11e6-825e-3475c1efa1df.jpg)

**Comment by davehunt** [comment]
Interesting, so this hides all log content by default and allows users to show the logs by clicking anywhere in the row? For my use case I prefer the log to be displayed by default, though I agree with @davidedelvento that I might prefer logs from passing tests to be hidden. Perhaps we could have a 'display log' link for these, and a 'hide log' link for any logs displayed?

We could also have 'show all logs' and 'hide all logs' links at the top of the page if users want to quickly toggle all logs. It then also sounds like we should have a preference for controlling if the logs are displayed initially, unless the 'hide all logs' does what we need there?

**Comment by hailin-xiao** [comment]
@davehunt Thanks for your reply. It's just a temporary workaround for this  as we don't have enough time  to do this. I definitely agree with your solution. It could be great for user to choose display or hide the logs. But it would be better to let each log have such an option. We're looking forward to the solution be committed. Thanks a log.

Hailin

**Comment by RibeiroAna** [comment]
Hi @davidedelvento, I just did a piece of code on the PR #46 that may help you when working on that issue, the first main change is that I've put an [ID](https://github.com/RibeiroAna/pytest-html/blob/filterTestsOutcomes/pytest_html/plugin.py#L157) on the "extra html" div and I did some [JS](https://github.com/RibeiroAna/pytest-html/blob/filterTestsOutcomes/pytest_html/resources/main.js#L194) (without using JQuery or any other library) that gets all the logs, maybe it is a good start point for you. My code was not merged yet, but I hope it will be soon, right @davehunt ?

**Comment by davidedelvento** [comment]
Hi @RibeiroAna that sounds good, having that ID will be helpful. I'll give it a try, hopefully tomorrow. Thanks.

**Comment by davidedelvento** [comment]
I've finally found some time to look at this (note that I'm not a javascript/html expert, so I plan to use very naive approach and a better one may be possible: suggestions welcome).

First, the ID that @RibeiroAna is using is not helpful for me, because it's in a separate `html.td` tag. My idea was to add to the `html.td` containing the log something like `id="1"` (with different number for each test), to hide the whole line with the captured out/err. Note the discrepancy between my use of the word "line" and the fact that this data is in a `html.td` container.

My problem is that the relevant `html.td` is placed into a separate `<tr class="extra">` by javascript (so `<tr class="extra">` does not exist into the generated report file), so I could hide the `td` but not the whole `tr` as I wanted. 

@davehunt Would it be ok to change the existing javascript to pull extra stuff (e.g. `id="1"`) from `<td class="extra">` to the containing `<tr class="extra">`? Or is that thing going away anyway for #29 and we should instead migrate to having a separate row anyway (which will be much easier for me to do)?

**Comment by davehunt** [comment]
I have no objections to any changes that do not regress the current functionality. Issue #29 will make sure the report is presented and functional when JavaScript is disallowed, but that doesn't mean that we can't have additional functionality when JavaScript is allowed. Note that id should be unique, and perhaps you'll be able to do what you need with data attributes instead?

**Comment by davidedelvento** [comment]
The fact that id should be unique is not a big deal, since you want each click on a `results-table-row` hide/show the relevant `extra` row for that row and not for something else.

The problem I have at the moment is that `split_extra_onto_two_rows()` generates two `extra` rows instead of only one as I expected looking at the browser. Inspecting the generated HTML, the first `extra` row is empty and not displayed, while the other with the actual content. 

I am not sure why this happens, and here is where I am stuck at the moment. Other than that, I've got this functionality working (if `test_id` is unique, otherwise I need to make it unique in some additional way).

See my fork for a clearer explanation (sometimes code is clearer than words...)

**Comment by davehunt** [comment]
The row split is being removed as part of the outcome filtering. Hopefully this will make your work a little easier when it lands.

Dave Hunt

**Comment by davidedelvento** [comment]
Yes I saw that work in progress, but I wanted to give collapsing a first shot against the current release. As a workaround, I can use data attributes as you say (instead of IDs) and my current code should work.

Is the row split removal imminent, or is there still a fair amount of work needed? On one hand, I don't want to add a functionality which will need to be rewritten as part of that removal, making it harder. On the other hand, if the removal is taking time and this functionality is ready, why wait?

**Comment by davehunt** [comment]
I think it will be ready by the end of this week.

**Comment by leitzler** [comment]
@davehunt any new eta? ;)

**Comment by davehunt** [comment]
The row split code was removed in 1.9.0, which should make this easier to implement. I am not currently working on this though - perhaps @davidedelvento is still interested?

**Comment by davidedelvento** [comment]
Yes, I am very interested and I plan to work on this.

**Comment by leitzler** [comment]
I created a PR proposal. I didn't add any "show all/hide all" links, but there are js-functions for them added. The entire javascript file could use some love, but I guess that's another issue :).

(didn't know if you were interested @davidedelvento, sorry)

**Comment by davidedelvento** [comment]
I tested your PR for my use case. Other than the missing of  "show all/hide all" links (which would be very convenient for me, in addition to the checkboxes that totally hide the entries in the table), the thing behaves very nicely. 
Hope it gets merged soon.
PS: I haven't found the time to look at the code yet, so can't comment on that.

**Comment by davehunt** [comment]
This landed in https://github.com/pytest-dev/pytest-html/commit/a8841db7c3dfcc2d4103ea30509512ba711b940c and will be available in the next release.
