### ISSUE TITLE
Test with errors mark as passed

### ISSUE THREAD

**Issue by KonstDud** [pytest-dev/pytest-html#778]
Hello!

Please tell me the change since the beginning of version 4 of displaying tests with errors in the report as passed correctly. Previously, such tests were not included in the passed category.

![image](https://github.com/pytest-dev/pytest-html/assets/74191944/e04e7ddc-16da-4a82-a340-de57e00d3203)

**Comment by jeffwright13** [comment]
Having an error associated with a test doesn't necessarily mean the test failed. There are really only 3 outcomes in pytest: pass, fail and skip. All the other test result categories you see in that final line of the console output (xpass, xfail, rerun, etc.) are based on various bits of logic checking various combinations of things that occur at various times in the test (during nthe setup, call and teardown phases). It is possible to have a "passing" test that results in an error.
```
@pytest.fixture
def error_fixt():
    raise Exception("Error in fixture")

def test0_pass_3_error_in_fixture(error_fixt):
    print("Test Pass 3!")
    assert True
```

You can see that this test would be marked as a Pass if no error occured (`assert True`). However, because of the error, it never even makes it that far; it fils during the setup of thet test itself:
```
$ pytest test_error.py
Inside hooks.py/pytest_addhooks
========================== test session starts ===========================
platform darwin -- Python 3.9.16, pytest-7.3.2, pluggy-1.0.0
rootdir: /Users/jwr003/coding/pytest-tui
configfile: pytest.ini
plugins: Faker-18.3.1, rerunfailures-12.0, metadata-3.0.0, html-4.0.3rc0, tui-2.0.0, oof-0.3.2
collected 1 item

test_error.py E                                                    [100%]

================================= ERRORS =================================
____________ ERROR at setup of test0_pass_3_error_in_fixture _____________

    @pytest.fixture
    def error_fixt():
>       raise Exception("Error in fixture")
E       Exception: Error in fixture

test_error.py:5: Exception
======================== short test summary info =========================
ERROR test_error.py::test0_pass_3_error_in_fixture - Exception: Error in fixture
============================ 1 error in 0.38s ============================
```

The question is, what does pytest-html do about this? Good question, let's find out:
```
) pytest test_error.py --html=report.html --self-contained-html
Inside hooks.py/pytest_addhooks
========================== test session starts ===========================
platform darwin -- Python 3.9.16, pytest-7.3.2, pluggy-1.0.0
rootdir: /Users/jwr003/coding/pytest-tui
configfile: pytest.ini
plugins: Faker-18.3.1, rerunfailures-12.0, metadata-3.0.0, html-4.0.3rc0, tui-2.0.0, oof-0.3.2
collected 1 item

test_error.py E                                                    [100%]

================================= ERRORS =================================
____________ ERROR at setup of test0_pass_3_error_in_fixture _____________

    @pytest.fixture
    def error_fixt():
>       raise Exception("Error in fixture")
E       Exception: Error in fixture

test_error.py:5: Exception
- Generated html report: file:///Users/jwr003/coding/pytest-tui/report.html -
======================== short test summary info =========================
ERROR test_error.py::test0_pass_3_error_in_fixture - Exception: Error in fixture
============================ 1 error in 0.46s ============================
```

The resulting report file simply shows a test categorized as "Error":
<img width="1811" alt="Screenshot 2023-11-22 at 9 47 31 AM" src="https://github.com/pytest-dev/pytest-html/assets/4308435/d8dbba71-8a0f-4d54-acb2-b457303dceba">

Looking at your report, it seems like maybe you actually have a test that produces an error and a test that produced a pass. What happens when you run the exact same tests without the pytest-html report? If you don't have that information, do you have the console output from that test run?

**Comment by KonstDud** [comment]
Thanks a lot!
This is probably due to the fact that my found errors are combined into one and an exception is raised at the end of the test.
When I run the exact same test without the pytest-html report:
1 passed and 1 error that was found during the test. Еhe test itself passed, albeit with an error
![image](https://github.com/pytest-dev/pytest-html/assets/74191944/a328207f-9677-46ce-9141-7d400dc276fa)

**Comment by jeffwright13** [comment]
Cool, so I think pytest-html results agree with yours?

**Comment by KonstDud** [comment]
Yes thank you! Very useful project for me
