### ISSUE TITLE
Capture logging by loglevel setting

### ISSUE THREAD

**Issue by westhomas** [pytest-dev/pytest-html#95]
Hey there! Great plugin!

I have a ton of debug logs (using `logging.debug`) that appear in the stdout. I'd love to capture this data in the html report.

I saw some reference to this in the issues backlog but I'm not seeing how it can be done. Is this a current feature?

**Comment by davehunt** [comment]
If the tests are failing then the full stdout should be included in the HTML report. If they're passing you may need to run pytest with `-rpP` to include this in the report. If you mean that you'd like to add this extra data as an asset in the report, the following snippet modified from the one in the README should help. You'll need to stash `log` somewhere so that it can be accessed from the `pytest_runtest_makereport` hook:

```python
import pytest
@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
    pytest_html = item.config.pluginmanager.getplugin('html')
    outcome = yield
    report = outcome.get_result()
    extra = getattr(report, 'extra', [])
    if report.when == 'call':
        xfail = hasattr(report, 'wasxfail')
        if (report.skipped and xfail) or (report.failed and not xfail):
            # add custom log to report on failure
            extra.append(pytest_html.extras.test(log))
        report.extra = extra
```

Let me know if you have any further questions. I'll leave this issue open for now.

**Comment by davehunt** [comment]
Closing due to lack of further details.
